name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  upload:
    name: 🚀 Deploy ZE CSGO
    runs-on: ubuntu-20.04
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync Leader whitelist
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_main_server }}
          username: ${{ secrets.ftp_main_username }}
          password: ${{ secrets.ftp_main_password }}
          port: ${{ secrets.ftp_main_port }}
          local-dir: othercfg/
          server-dir: addons/sourcemod/configs/othercfg/

